version: "2"
services:
  db:
    container_name: "db"
    image: couchbase
    Ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
  web:
    image: jboss/wildfly
    environment:
      - COUCHBASE_URI=db
    ports:
      - 8080:8080
      - 9990:9990
  backend:
    image: prasadrevanaki/MediwareOnline050218-0.0.1
    ports: 
      - 8080:38230